name: yUtils
version: 1.0
main: me.flame.utils.Main
author: flame_tuner
description: Plugin feito para gerenciar Permissions, Compras, Banimentos, Tags e Scoreboards
commands:
  groupset:
    description: Comando utilizado para mudar o grupo de pessoas
  giveyoutuber:
    description: Comando utilizado por admins para dar youtuber
  kick:
    description: Comando utilizado para kickar pessoas
  ban:
    description: Comando utilizado para banir pessoas
  mute:
    description: Comando utilizado para mutar pessoas
  unban:
    description: Comando utilizado para desbanir pessoas
  unmute:
    description: Comando utilizado para desmutar pessoas
  tempban:
    description: Comando utilizado para banir temporariamente
  tempmute:
    description: Comando utilizado para mutar temporariamente