name: yUtils
version: 2.4.4
main: me.flame.utils.Main
author: GustavoInacio
description: Plugin feito para gerenciar Permissions, Compras, Banimentos, Tags e Scoreboards
commands:
  groupset:
    description: Comando utilizado para mudar o grupo de pessoas
  giveyoutuber:
    description: Comando utilizado por admins para dar youtuber
  kick:
    description: Comando utilizado para kickar pessoas
  ban:
    description: Comando utilizado para banir pessoas
  mute:
    description: Comando utilizado para mutar pessoas
  unban:
    description: Comando utilizado para desbanir pessoas
  unmute:
    description: Comando utilizado para desmutar pessoas
  tempban:
    description: Comando utilizado para banir temporariamente
  tempmute:
    description: Comando utilizado para mutar temporariamente
  givevip:
    description: Comando utilizado para dar vips
  addtorneio:
    description: Comando utilizado para adicionar players ao torneio
  tag:
    description: Comando utilizado para mudar a tag
  fake:
    description: Comando utilizado para mudar o nick
  account:
    description: Comando utilizado para saber informacoes sobre players
  rank:
    description: Comando utilizado para saber informacoes sobre ligas
  givekit:
    description: Comando utilizado para dar kits de HG aos players
  giveeventvip:
    description: Comando utilizado para dar kits de HG aos players
  iw3:
    description: IW3 Webstore Plugin Commands
    default: op
    permission: iw3.commands
  iw4:
    description: IW4 e-Commerce Plugin commands
    default: op
  compras:
    description: IW3 Player Command
    default: true